# Generated by Django 4.2.2 on 2023-09-30 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='depart',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phn',
            field=models.IntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
